apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
  creationTimestamp: "2019-10-28T23:19:55Z"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-role-knative
  resourceVersion: "1381"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/gloo-role-knative
  uid: 73754db9-f9d9-11e9-968e-0a094f6cd970
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  - endpoints
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
- apiGroups:
  - gloo.solo.io
  - enterprise.gloo.solo.io
  resources:
  - settings
  - upstreams
  - upstreamgroups
  - proxies
  - virtualservices
  - routetables
  - authconfigs
  verbs:
  - '*'
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - clusteringresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - clusteringresses/status
  verbs:
  - update
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses/status
  verbs:
  - update
