apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "15"
  creationTimestamp: "2019-10-28T23:19:55Z"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-role-binding-knative-gloo-system
  resourceVersion: "1382"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/gloo-role-binding-knative-gloo-system
  uid: 737b5bf0-f9d9-11e9-968e-0a094f6cd970
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gloo-role-knative
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
- kind: ServiceAccount
  name: discovery
  namespace: gloo-system
- kind: ServiceAccount
  name: gloo
  namespace: gloo-system
